### ISSUE TITLE
Post endpoints for the related entities don't bust the cache.

### ISSUE THREAD

**Issue by muditjuneja** [patrixr/strapi-middleware-cache#13]
Let consider this relation: A Book can have multiple authors
Steps: 
1. My endpoint for fetching the books is HTTP://localhost:1337/books. Data is being cached here. This endpoint also fetches the authors data from the authors collection.
2. Go to the admin panel and update any author from that book.
3. Call the get books endpoint, it brings data from the cache but the updated author info is not available.
4. Go to the admin panel and update any book
5. Now the cache has been busted.

How can this be achieved? Is there a way to manually bust the cache via another endpoint just like graphql has exposed its playground? Help needed.

PS: I am using strapi with mongo.

**Comment by patrixr** [comment]
Hi @muditjuneja 

That's a good point, the caching is currently simple and lean, and doesn't support anything like that. The cache expiration is what would come in play here to allow the data to change.

Regarding manually busting the cache, there is none apart from making a `post` request.
Maybe the middleware could attach a method to strapi to bust the cache ?

e.g
```javascript
// in your controller
strapi.middlewares.cache.bust(model, id);
```

@derrickmehaffy Would this ☝️  follow (or break) strapi best practices ? Any suggestions ?

Supporting relation changes would significantly increase the scope of this project, and might enforce reads on the database, which I'm hoping to avoid (prefer keeping it lean).

**Comment by derrickmehaffy** [comment]
To this I'm not sure, let me ask our backend engineering team to see what they think.

**Comment by derrickmehaffy** [comment]
From @alexandrebodin it's best to not inject something into the main Strapi instance but create a service though I cannot remember off the top of my head if middlewares even have support for services. In this case I'm not sure of the best practice here since we are kinda in unknown territory. I think the bust would need to be aware of any relations during the post request.

@patrixr I don't -think- you should need to do any DB calls since the `strapi.models.someModel` or `strapi.plugins['users-permissions'].models.user` (users-permissions is just an example you would have to iterate the `strapi.plugins[*].models` ) has all the attributes including the relational fields. We should be able to tell when something is posted and bust any higher level cache but it would add some complexity.

**Comment by derrickmehaffy** [comment]
Just an example using `yarn strapi console` and typing in `strapi.plugins['users-permissions'].models.user`

Gives this:

```
...
  allAttributes: {
    username: {
      type: 'string',
      minLength: 3,
      unique: true,
      configurable: false,
      required: true
    },
    email: {
      type: 'email',
      minLength: 6,
      configurable: false,
      required: true
    },
    provider: { type: 'string', configurable: false },
    password: {
      type: 'password',
      minLength: 6,
      configurable: false,
      private: true
    },
    resetPasswordToken: { type: 'string', configurable: false, private: true },
    confirmed: { type: 'boolean', default: false, configurable: false },
    blocked: { type: 'boolean', default: false, configurable: false },
    role: {
      model: 'role',
      via: 'users',
      plugin: 'users-permissions',
      configurable: false
    },
    created_by: { model: 'user', plugin: 'admin' },
    updated_by: { model: 'user', plugin: 'admin' },
    created_at: { type: 'timestamp' },
    updated_at: { type: 'timestamp' }
  }
```

And we can tell by iterating the keys in the `allAttributes` if there is a related model and the plugin (if any)

**Comment by patrixr** [comment]
@derrickmehaffy  Thanks for this ! 

I was originally thinking we would need to read the DB to bust individual caches of hasMany relationships. However it could simply bust the entire cache for that model (including collections). Which is a bit agressive, but I guess the behaviour already is a bit like that.

**Comment by derrickmehaffy** [comment]
Indeed, it's already aggressive so no real drawback here that I can see.

**Comment by vuoriv** [comment]
We also dealing with this issue. Do you have plans or timetable for it? Thanks!

**Comment by julesrenaud** [comment]
Adding this feature would enhance the middleware a lot. @patrixr I can start working on this if you don't mind!

**Comment by patrixr** [comment]
@julesrenaud You're more than welcome to ! I sadly haven't had much time to focus on this middleware so happy to see the strapi community contributing.

by the way, I am available on the Strapi slack for any questions. Also thinking of adding some contributors to the repo since there seems to be a fair amount of people using this now (I never thought anyone would to be honest)

**Comment by derrickmehaffy** [comment]
@patrixr always happen to help where I can. Can't promise I'll always have the free time to validate PRs but I can certainly help with reviewing and testing

**Comment by patrixr** [comment]
@derrickmehaffy Many thanks, I've sent you an invite
