### ISSUE TITLE
Cache Single Types or disable pluralize

### ISSUE THREAD

**Issue by MrTheFirst** [patrixr/strapi-middleware-cache#17]
How i can disable pluralize plugin or cache single types like **menu**, **main-page**, **news-page**? When i add **menu** to models array plugin modify this to **menus**

**Comment by patrixr** [comment]
Hi @MrTheFirst 

The reason it pluralizes it, is because Strapi does that on its endpoints. So a `Menu` Content-Type would be fetched via the `/menus` endpoints.

I used the same `pluralize` package as Strapi does to match the endpoints, so that it wouldn't matter whether you wrote "menu" or "menus" in the configuration

e.g from the documentation

![Screenshot 2020-09-28 at 9 32 32 AM](https://user-images.githubusercontent.com/1822532/94382094-05301680-016e-11eb-9918-5ed215807ff2.png)


If the endpoint Strapi generates is actually `/menu` then there would be a mistmatch indeed. Could you let me know if that's the case ?

Thanks : )

**Comment by MrTheFirst** [comment]
Thanks for reply, @patrixr!
Yes, strapi generate endpoints for `single types` collections without `pluralize` plugin.
See [documentation](https://strapi.io/documentation/v3.x/content-api/api-endpoints.html#endpoints):
<img width="928" alt="Screenshot at Oct 02 11-23-08" src="https://user-images.githubusercontent.com/4955590/94903286-409a5000-04a2-11eb-8914-358f3de150f6.png">

I think for a quick solution, you can simply remove the `pluralize` from the plugin or add a flag to model config:
```
module.exports = ({ env }) => ({
  settings: {
    cache: {
      enabled: true,
      models: [
        {
          singleType: true // default false
          model: 'homepage',
        },
      ],
    },
  },
});
```

**Comment by patrixr** [comment]
Ah great ! Removing it might cause plural models to fail, but we can definitely add in the option :)

**Comment by MrTheFirst** [comment]
@patrixr tanks! I look forward to! Api performance suffers from single collections ...

**Comment by patrixr** [comment]
@MrTheFirst 

I just pushed version `1.0.9` on NPM with support for single types. Readme is also up to date.

Thanks for bringing me up to date with single types, I had never used them before. Let me know how the middleware works out for yo now : )

**Comment by MrTheFirst** [comment]
@patrixr thanks! Everything works, no problems were found

**Comment by patrixr** [comment]
Lovely :)
