### ISSUE TITLE
[FR] Add option to disable initial logging

### ISSUE THREAD

**Issue by derrickmehaffy** [patrixr/strapi-middleware-cache#5]
While doing some testing on my own project, I noticed the initial logging could quickly get out of hand (for reference I have 90-ish models in my project, and am only caching about 20% of them)

![image](https://user-images.githubusercontent.com/8593673/82883490-58ac0280-9ef7-11ea-89f5-55d3daa27eea.png)

I'm thinking it might be better to add some kind of config option to disable the verbosity (or at least decrease it) of the logging.

**Comment by patrixr** [comment]
Hey @derrickmehaffy 

I hadn't thought of it much, given that it only logs the routes once at startup.

It uses Strapi's internal logger, so changing the log level of the project could be the way to go. We could lower the log level down to `debug` for more flexibility

How would you feel about about that solution ? I'm not opposed to a config option either. Would like to know your preference since you're the one dealing with this scenario :)

**Comment by derrickmehaffy** [comment]
I think attaching it to the log level would be fine, the logging is useful in development but as you move into production (especially at scale with a central logging solution) this could quickly get out of hand.

In my case I deploy Strapi to 3 virtual machines, each using a pm2 cluster of 4 instances, so these log messages are duplicated 12 times.

During an automated staging environment that can deploy multiple times per day this could end up being thousands of lines a day being sent to my Graylog instance (what I use for log management)

**Comment by patrixr** [comment]
@derrickmehaffy 

I ended up doing both

- downgrade the middleware's log level to `debug`
- added a `logs: true|false` option to the config

Should be available after upgrading to `1.0.4` : )

**Comment by derrickmehaffy** [comment]
Tested and works great, thank you
